/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer User
 */
public class MagicalMathMethods extends javax.swing.JFrame {

    /**
     * Creates new form MagicalMathMethods
     */
    public MagicalMathMethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblLargest = new javax.swing.JLabel();
        btnLargest = new javax.swing.JButton();
        txtLarge1 = new javax.swing.JTextField();
        lblLargestValue = new javax.swing.JLabel();
        lblSmallest = new javax.swing.JLabel();
        txtSmall1 = new javax.swing.JTextField();
        btnSmallest = new javax.swing.JButton();
        lbSmallestValue = new javax.swing.JLabel();
        lblPower = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        btnPower = new javax.swing.JButton();
        lblPowerValue = new javax.swing.JLabel();
        lblHypot = new javax.swing.JLabel();
        txtHypot1 = new javax.swing.JTextField();
        btnHypot = new javax.swing.JButton();
        lblHypotValue = new javax.swing.JLabel();
        lblRDown = new javax.swing.JLabel();
        txtRDown = new javax.swing.JTextField();
        btnRDown = new javax.swing.JButton();
        lblRDownValue = new javax.swing.JLabel();
        lblRUp = new javax.swing.JLabel();
        txtRUp = new javax.swing.JTextField();
        btnRUp = new javax.swing.JButton();
        lblRUpValue = new javax.swing.JLabel();
        lblSquareRoot = new javax.swing.JLabel();
        btnSquareRoot = new javax.swing.JButton();
        lblSquareRootValue = new javax.swing.JLabel();
        txtSmall2 = new javax.swing.JTextField();
        txtLarge2 = new javax.swing.JTextField();
        txtPower = new javax.swing.JTextField();
        txtHypot2 = new javax.swing.JTextField();
        lblRadians = new javax.swing.JLabel();
        txtSquareRoot = new javax.swing.JTextField();
        txtRadians = new javax.swing.JTextField();
        btnRadians = new javax.swing.JButton();
        lblRadiansValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setText("Magical Math Methods");

        lblLargest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLargest.setText("Enter two numbers. The program will output the largest of the two numbers. ");

        btnLargest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLargest.setText("Largest");
        btnLargest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLargestActionPerformed(evt);
            }
        });

        txtLarge1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblLargestValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLargestValue.setText("   ....");

        lblSmallest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSmallest.setText("Enter two numbers. The program will output the smallest of the two numbers. ");

        txtSmall1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnSmallest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSmallest.setText("Smallest");
        btnSmallest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmallestActionPerformed(evt);
            }
        });

        lbSmallestValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbSmallestValue.setText("   ....");

        lblPower.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPower.setText("Enter two numbers and click the button. The program will display the value rounded down to the nearest integer: ");

        txtBase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnPower.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPower.setText("to the power of ");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });

        lblPowerValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPowerValue.setText("   ....");

        lblHypot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHypot.setText("Enter the length of weo sides of a right angle triangle. The program will display the hypotenuse of triangle.");

        txtHypot1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnHypot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHypot.setText("hypotenuse");
        btnHypot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHypotActionPerformed(evt);
            }
        });

        lblHypotValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblHypotValue.setText("   ....");

        lblRDown.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRDown.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer.");

        txtRDown.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnRDown.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRDown.setText("Rounded Down");
        btnRDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRDownActionPerformed(evt);
            }
        });

        lblRDownValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRDownValue.setText("   ....");

        lblRUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRUp.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer.");

        txtRUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnRUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRUp.setText("Rounded Up");
        btnRUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUpActionPerformed(evt);
            }
        });

        lblRUpValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRUpValue.setText("   ....");

        lblSquareRoot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSquareRoot.setText("Enter an integer. The program will display the square root of the integer.");

        btnSquareRoot.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSquareRoot.setText("Square Root");
        btnSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareRootActionPerformed(evt);
            }
        });

        lblSquareRootValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSquareRootValue.setText("   ....");

        txtSmall2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtLarge2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPower.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtHypot2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblRadians.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRadians.setText("Enter an angle in degrees . The program will display the angle in radians:");

        txtSquareRoot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtRadians.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnRadians.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRadians.setText("In Radians");
        btnRadians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadiansActionPerformed(evt);
            }
        });

        lblRadiansValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRadiansValue.setText("   ....");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(txtRUp, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRUp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(lblRUpValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(txtSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(lblSquareRootValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(txtSmall1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(txtSmall2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSmallest, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(txtPower, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPower)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(txtRDown, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRDown)
                        .addGap(91, 91, 91)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSmallestValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPowerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHypotValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblRDownValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(txtRadians, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290)
                .addComponent(btnRadians, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(lblRadiansValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(txtLarge1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(txtLarge2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(btnLargest, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(lblLargestValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(txtHypot1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(txtHypot2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(btnHypot, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPower)
                            .addComponent(lblRDown)
                            .addComponent(lblHypot)
                            .addComponent(lblRUp)
                            .addComponent(lblSquareRoot)
                            .addComponent(lblRadians)
                            .addComponent(lblLargest)
                            .addComponent(lblSmallest))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblTitle)
                .addGap(44, 44, 44)
                .addComponent(lblLargest)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLargestValue, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLarge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLarge2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLargest)))
                .addGap(18, 18, 18)
                .addComponent(lblSmallest)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSmallest)
                    .addComponent(lbSmallestValue)
                    .addComponent(txtSmall1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSmall2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(lblPower)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPower)
                        .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPowerValue))
                    .addComponent(txtPower, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblHypot)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHypot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHypot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHypotValue)
                            .addComponent(btnHypot))))
                .addGap(42, 42, 42)
                .addComponent(lblRDown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnRDown)
                        .addComponent(lblRDownValue))
                    .addComponent(txtRDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblRUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRUp)
                    .addComponent(txtRUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRUpValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lblSquareRoot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSquareRootValue)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSquareRoot)
                        .addComponent(txtSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRadians)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRadiansValue)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRadians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRadians))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHypotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHypotActionPerformed
       // Math.hypot(double d1, double d2)
    }//GEN-LAST:event_btnHypotActionPerformed

    private void btnSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareRootActionPerformed
      // Math.sqrt(double d)
    }//GEN-LAST:event_btnSquareRootActionPerformed

    private void btnLargestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLargestActionPerformed
        double large1 = Double.parseDouble(txtLarge1.getText());    
        double large2 = Double.parseDouble(txtLarge2.getText());
        double largest = Math.max(large1, large2);
        lblLargestValue.setText(String.valueOf(largest));
    }//GEN-LAST:event_btnLargestActionPerformed

    private void btnSmallestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmallestActionPerformed
        double small1 = Double.parseDouble(txtSmall1.getText());    
        double small2 = Double.parseDouble(txtSmall2.getText());
        double smallest = Math.min(small1, small2);
        lbSmallestValue.setText(String.valueOf(smallest));
    }//GEN-LAST:event_btnSmallestActionPerformed

    private void btnRadiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadiansActionPerformed
        //Math.toRadians(double d)
    }//GEN-LAST:event_btnRadiansActionPerformed

    private void btnRDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRDownActionPerformed
        //Math.floor(double d)
    }//GEN-LAST:event_btnRDownActionPerformed

    private void btnRUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUpActionPerformed
        //Math.ceil(double d)
    }//GEN-LAST:event_btnRUpActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
      // Math.pow(double d1, double d2)
        double num1 = Double.parseDouble(txtBase.getText());    
        double num2 = Double.parseDouble(txtPower.getText());
        double power2 = Math.pow(num1, num2);
        lblPowerValue.setText(String.valueOf(power2));
    }//GEN-LAST:event_btnPowerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagicalMathMethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagicalMathMethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHypot;
    private javax.swing.JButton btnLargest;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnRDown;
    private javax.swing.JButton btnRUp;
    private javax.swing.JButton btnRadians;
    private javax.swing.JButton btnSmallest;
    private javax.swing.JButton btnSquareRoot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbSmallestValue;
    private javax.swing.JLabel lblHypot;
    private javax.swing.JLabel lblHypotValue;
    private javax.swing.JLabel lblLargest;
    private javax.swing.JLabel lblLargestValue;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblPowerValue;
    private javax.swing.JLabel lblRDown;
    private javax.swing.JLabel lblRDownValue;
    private javax.swing.JLabel lblRUp;
    private javax.swing.JLabel lblRUpValue;
    private javax.swing.JLabel lblRadians;
    private javax.swing.JLabel lblRadiansValue;
    private javax.swing.JLabel lblSmallest;
    private javax.swing.JLabel lblSquareRoot;
    private javax.swing.JLabel lblSquareRootValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtHypot1;
    private javax.swing.JTextField txtHypot2;
    private javax.swing.JTextField txtLarge1;
    private javax.swing.JTextField txtLarge2;
    private javax.swing.JTextField txtPower;
    private javax.swing.JTextField txtRDown;
    private javax.swing.JTextField txtRUp;
    private javax.swing.JTextField txtRadians;
    private javax.swing.JTextField txtSmall1;
    private javax.swing.JTextField txtSmall2;
    private javax.swing.JTextField txtSquareRoot;
    // End of variables declaration//GEN-END:variables
}
